version: "3"

services: 
  toolchain:
    build: ./toolchain
    # command: 
    #   cp -r /riscv-tests/benchmarks /tests
    #   cp -r /riscv-tests/isa /tests
    volumes: 
      - ./tests:/tests:rw

  simulator:
    build: ./simulator
    volumes: 
      - ./tests:/tests:rw
    depends_on: 
      - toolchain